
version: 2

models:
    - name: test_model
      description: "using main table"
      columns:
          - name: date
            description: "The primary key for this table"
            tests:
                - not_null
